version: 2.1
orbs:
  node: circleci/node@4.1.0
  codecov: codecov/codecov@1.1.3

jobs:
  test:
    parameters:
      version:
        type: string
    executor:
      name: node/default
      tag: << parameters.version >>
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
      - when: 
          condition:
            equal: ["current", << parameters.version >>]
          steps:
            - codecov/upload

workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              version: ["12.20", "14.15", "current"]
